spring:
  security:
    user:
      name: buzz
      password: infinity
  datasource:
    generate-unique-name: false
    name: tacocloud

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      - abcdef1: 10
      - abcdef2: 11
      - abcdef3: 12

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
